version: '2'
services:
  murmur:
    image: q84fh/murmur:latest
    container_name: murmur
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    restart: always
    volumes:
      - ./certs:/var/lib/murmur/certs
      - data:/var/lib/murmur
    environment:
      #- MUMBLE_SUPW=secretpassword

      # How many login attempts do we tolerate from one IP
      # inside a given timeframe before we ban the connection?
      # Note that this is global (shared between all virtual servers), and that
      # it counts both successfull and unsuccessfull connection attempts.
      # Set either Attempts or Timeframe to 0 to disable.
      #- AUTOBANATTEMPTS=10
      #- AUTOBANTIMEFRAME=120
      #- AUTOBANTIME=300

      # Welcome message sent to clients when they connect.
      - WELCOMETEXT="<br />Welcome to this server running <b>Murmur</b>.<br />Enjoy your stay!<br />"

      # Password to join server.
      # - SERVERPASSWORD=

      # Maximum bandwidth (in bits per second) clients are allowed
      # to send speech at.
      - BANDWIDTH=72000

      # Maximum number of concurrent clients allowed.
      - USERS=100

      # Amount of users with Opus support needed to force Opus usage, in percent.
      # 0 = Always enable Opus, 100 = enable Opus if it's supported by all clients.
      # - OPUSTHRESHOLD=100
 
      # Maximum depth of channel nesting. Note that some databases like MySQL using
      # InnoDB will fail when operating on deeply nested channels.
      #- channelnestinglimit=10
 
      # Regular expression used to validate channel names.
      # (Note that you have to escape backslashes with \ )
      #- channelname=[ \\-=\\w\\#\\[\\]\\{\\}\\(\\)\\@\\|]+

      # Regular expression used to validate user names.
      # (Note that you have to escape backslashes with \ )
      #- username=[-=\\w\\[\\]\\{\\}\\(\\)\\@\\|\\.]+

      # Maximum length of text messages in characters. 0 for no limit.
      #textmessagelength=5000

      # Maximum length of text messages in characters, with image data. 0 for no limit.
      #imagemessagelength=131072

      # Allow clients to use HTML in messages, user comments and channel descriptions?
      #allowhtml=true

      # Murmur retains the per-server log entries in an internal database which
      # allows it to be accessed over D-Bus/ICE.
      # How many days should such entries be kept?
      # Set to 0 to keep forever, or -1 to disable logging to the DB.
      #logdays=31

# To enable public server registration, the serverpassword must be blank, and
# this must all be filled out.
# The password here is used to create a registry for the server name; subsequent
# updates will need the same password. Don't lose your password.
# The URL is your own website, and only set the registerHostname for static IP
# addresses.
# Only uncomment the 'registerName' parameter if you wish to give your "Root" channel a custom name.
#
#registerName=Mumble Server
#registerPassword=secret
#registerUrl=http://mumble.sourceforge.net/
#registerHostname=

# If this option is enabled, the server will announce its presence via the 
# bonjour service discovery protocol. To change the name announced by bonjour
# adjust the registerName variable.
# See http://developer.apple.com/networking/bonjour/index.html for more information
# about bonjour.
#bonjour=True

# If you have a proper SSL certificate, you can provide the filenames here.
# Otherwise, Murmur will create it's own certificate automatically.
#sslCert=/var/lib/murmur/certs/cert.crt
#sslKey=/var/lib/murmur/certs/cert.key

# If this options is enabled, only clients which have a certificate are allowed
# to connect.
#certrequired=False

# If enabled, clients are sent information about the servers version and operating
# system.
#sendversion=True

volumes:
  data:
    driver: local


